version: 2.1

jobs:
  build_and_deploy:
    description: Build & Deploy
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Build & Deploy
          command: |
            npm install
            npx firebase-tools --token "$FIREBASE_TOKEN" use ramp-instant-demo

            export REACT_APP_DEMO_APP_INSTANCE=DEV
            export REACT_APP_NETWORK_NAME=Rinkeby
            export REACT_APP_TOKEN_NAME=DUMMY
            export REACT_APP_URL=https://ri-widget-dev.firebaseapp.com/
            export REACT_APP_DOCS_URL=https://ri-docs-dev.firebaseapp.com
            export REACT_APP_REFUNDED_FEES_API_TOKEN=cwftrxqch5239yzjcr7hbspmhh8obuz3jgdqxwog
            npm run build
            npx firebase-tools --token "$FIREBASE_TOKEN" deploy --only "hosting:ri-demo-dev"

            export REACT_APP_DEMO_APP_INSTANCE=STAGING
            export REACT_APP_NETWORK_NAME=Rinkeby
            export REACT_APP_TOKEN_NAME=TEST
            export REACT_APP_URL=https://ri-widget-staging.firebaseapp.com/
            export REACT_APP_DOCS_URL=https://ri-docs-staging.firebaseapp.com
            export REACT_APP_REFUNDED_FEES_API_TOKEN=j4z5gn7eh7uvbdgpd7c7wgkq4msuqrgs4xq4jutv
            npm run build
            npx firebase-tools --token "$FIREBASE_TOKEN" deploy --only "hosting:ri-demo-staging"

            export REACT_APP_DEMO_APP_INSTANCE=STAGING_ROPSTEN
            export REACT_APP_NETWORK_NAME=Ropsten
            export REACT_APP_TOKEN_NAME=DUMMY
            export REACT_APP_URL=https://ri-widget-staging-ropsten.firebaseapp.com/
            export REACT_APP_DOCS_URL=https://ri-docs-staging-ropsten.firebaseapp.com
            npm run build
            npx firebase-tools --token "$FIREBASE_TOKEN" deploy --only "hosting:ri-demo-staging-ropsten"

            export REACT_APP_DEMO_APP_INSTANCE=STAGING_KOVAN
            export REACT_APP_NETWORK_NAME=Kovan
            export REACT_APP_TOKEN_NAME=DUMMY
            export REACT_APP_URL=https://ri-widget-staging-kovan.firebaseapp.com/
            export REACT_APP_DOCS_URL=https://ri-docs-staging-kovan.firebaseapp.com
            npm run build
            npx firebase-tools --token "$FIREBASE_TOKEN" deploy --only "hosting:ri-demo-staging-kovan"

            export REACT_APP_DEMO_APP_INSTANCE=STAGING_GOERLI
            export REACT_APP_NETWORK_NAME=Goerli
            export REACT_APP_TOKEN_NAME=DUMMY
            export REACT_APP_URL=https://ri-widget-staging-goerli.firebaseapp.com/
            export REACT_APP_DOCS_URL=https://ri-docs-staging-goerli.firebaseapp.com/
            npm run build
            npx firebase-tools --token "$FIREBASE_TOKEN" deploy --only "hosting:ri-demo-staging-goerli"

            export REACT_APP_DEMO_APP_INSTANCE=PROD
            export REACT_APP_NETWORK_NAME=mainnet
            export REACT_APP_TOKEN_NAME=DAI
            export REACT_APP_URL=https://widget-instant.ramp.network/
            export REACT_APP_DOCS_URL=https://docs-instant.ramp.network
            npm run build
            npx firebase-tools --token "$FIREBASE_TOKEN" deploy --only "hosting:ri-demo-prod"

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy
